Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Networkteam.Neos.PencilCase:PencilCase':
            resource: resource://Networkteam.Neos.PencilCase/Public/PencilCase/Plugin.js
        stylesheets:
          'Networkteam.Neos.PencilCase:PencilCase':
            resource: resource://Networkteam.Neos.PencilCase/Public/PencilCase/Plugin.css
      frontendConfiguration:
        Networkteam.Neos.PencilCase:
          headingOptions:
          customOptions:
